### ISSUE TITLE
上传图片失败

### ISSUE THREAD

**Issue by zhuaowei** [Redns/picgo-plugin-imagebed#1]
安装插件配置好之后，上传图片失败。

服务器是用Nginx把12121端口代理到了 `http://upload.域名.top/`，网页控制台可以上传成功。

这里是报错的日志：

```
2022-08-13 19:22:23 [PicGo ERROR] 
------Error Stack Begin------
Error: StatusCodeError: 400 - ""
    at Object.handle (C:\Users\DELL\AppData\Roaming\picgo\node_modules\picgo-plugin-imagebed\src\index.js:68:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
-------Error Stack End------- 
```

**Comment by Redns** [comment]
去掉域名末尾的 `/` 试试

**Comment by zhuaowei** [comment]
去掉确实可以用了，感谢
